### ISSUE TITLE
Eror when using mariadb

### ISSUE THREAD

**Issue by Just-ElC** [TuxCoding/FastLogin#1265]
### What happened?

I'm using the 'Ketting' hybrid kernel, when I start the server I get an error saying that it cannot connect to mariadb

### Steps to reproduce

1. Setup 'Ketting' server
2. Install FastLogin plugin on server and velocity
3. Get error when server loading

### Plugin list

BlueMap, PlaceholderAPI, AntiDisconnectSpam, spark, StatusPlugin, Vault, WorldsColor, ProtocolLib, Chatty, SkinsRestorer, WorldEdit, Essentials, AFKPlus, AuthMe, TAB, AFKPlusPAPI, F3NPerm, WorldGuard, CoreProtect, FastLogin, GSit

### Server log

https://pastebin.com/tVXBg81W

### Plugin version

last

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
There is no driver for MariaDB in the Bukkit version. You have to switch to the MySQL driver provided by Spigot which should still be compatible with MariaDB server.

**Comment by Just-ElC** [comment]
> There is no driver for MariaDB in the Bukkit version of FastLogin. You have to switch to the MySQL driver provided by Spigot which should still be compatible with MariaDB server.

But Velocity support only mariadb

**Comment by games647** [comment]
Yes but then the proxy module of Fastlogin is responsible for the database that you setup like this:

https://github.com/games647/FastLogin?tab=readme-ov-file#bungeecordwaterfall-or-velocity

**Comment by enesop** [comment]
I am also getting an error using mariadb on Velocity version Velocity 3.4.0-SNAPSHOT (git-1652d44f-b469)
```
[04:51:24 WARN] [fastlogin]: This driver mariadb is not supported on this platform
[04:51:24 WARN] [fastlogin]: Please choose either MySQL (Spigot, BungeeCord), SQLite (Spigot, Sponge) or MariaDB (Sponge, Velocity)
java.lang.ClassNotFoundException: mariadb
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.checkDriver(FastLoginCore.java:252) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:211) ~[?:?]
        at com.github.games647.fastlogin.velocity.FastLoginVelocity.onProxyInitialization(FastLoginVelocity.java:95) ~[?:?]
        at com.github.games647.fastlogin.velocity.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:677) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:542) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
````

**Comment by games647** [comment]
@enesop That appears to be an outdated plugin version, because that line of code doesn't exist anymore.

**Comment by enesop** [comment]
FastLogin 1.1, Velocity 3.4.0-SNAPSHOT (git-1652d44f-b469)
```
[10:02:36 WARN] [fastlogin]: This driver mariadb is not supported on this platform
[10:02:36 WARN] [fastlogin]: Please choose either MySQL (Spigot, BungeeCord), SQLite (Spigot, Sponge) or MariaDB (Sponge, Velocity)
java.lang.ClassNotFoundException: mariadb
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:412) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.checkDriver(FastLoginCore.java:252) ~[?:?]
        at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:211) ~[?:?]
        at com.github.games647.fastlogin.velocity.FastLoginVelocity.onProxyInitialization(FastLoginVelocity.java:95) ~[?:?]
        at com.github.games647.fastlogin.velocity.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:677) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:542) ~[proxy.jar:3.4.0-SNAPSHOT (git-1652d44f-b469)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by enesop** [comment]
Is this released on github?

**Comment by games647** [comment]
The newest code is on GitHub, but the built version can be retrieved from here:

https://github.com/games647/FastLogin?tab=readme-ov-file#development-builds
