### ISSUE TITLE
I am using fastlogin + authme and i cant join my server using geyser. 

### ISSUE THREAD

**Issue by zonicisalive** [TuxCoding/FastLogin#862]
### What happened?

I am using fastlogin + authme and i cant join my server using geyser with my mobile when i remove fastlogin and authme i can join why.

### What did you expect?

idk

### Steps to reproduce

idk

### Plugin list

AuthMe, CoreProtect, DriveBackupV2, FastLogin, floodgate, Geyser-Spigot, GriefPrevention, PlaceholderAPI, PlayerKits, ProtocolSupport, SimpleTpa*

### Configuration file

https://www.toptal.com/developers/hastebin/ituxoboxed.yaml

### Server log

[14:47:08] [ServerMain/INFO]: Building unoptimized datafixer
[14:47:18] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:47:31] [ServerMain/INFO]: Loaded 7 recipes
[14:47:42] [Server thread/INFO]: Starting minecraft server version 1.19
[14:47:42] [Server thread/INFO]: Loading properties
[14:47:43] [Server thread/INFO]: This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
[14:47:43] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:47:43] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:47:46] [Server thread/INFO]: Default game type: SURVIVAL
[14:47:46] [Server thread/INFO]: Generating keypair
[14:47:47] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25834
[14:47:47] [Server thread/INFO]: Using epoll channel type
[14:47:47] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[14:47:47] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[14:47:51] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_19_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[14:48:16] [Server thread/WARN]: Legacy plugin SimpleTpa v6.1 does not specify an api-version.
[14:48:18] [Server thread/INFO]: [FastLogin] Initialize logging service
[14:48:18] [Server thread/INFO]: [CoreProtect] Loading CoreProtect v21.2
[14:48:18] [Server thread/INFO]: [SimpleTpa] Loading SimpleTpa v6.1
[14:48:18] [Server thread/INFO]: [AuthMe] Loading AuthMe v5.6.0-beta2-b2453
[14:48:18] [Server thread/INFO]: [floodgate] Loading floodgate v2.2.0-SNAPSHOT (b70-6e2c19f)
[14:48:20] [Server thread/INFO]: [floodgate] Took 2,502ms to boot Floodgate
[14:48:20] [Server thread/INFO]: [ProtocolSupport] Loading ProtocolSupport v1.18.1-1
[14:48:20] [Server thread/INFO]: [ProtocolSupport] File log is not enabled
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ╔══════════════════════════════════════════════════════════════════╗
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║                               ERROR                               
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║   Unsupported platform or version git-Paper-81 (MC: 1.19)
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║                                                                   
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║   This version of plugin only supports                            
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║   server minecraft version 1.18.1
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║   and following platforms:                                        
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║   - Spigot (https://www.spigotmc.org/)                            
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║   - Paper (https://papermc.io/)                                   
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║                                                                   
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║                                                                   
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ║       https://github.com/ProtocolSupport/ProtocolSupport/         
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] ╚══════════════════════════════════════════════════════════════════╝
[14:48:20] [Server thread/ERROR]: [ProtocolSupport] Platform init failed
java.lang.UnsupportedOperationException: No supported platform detected
	at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:19) ~[ProtocolSupport.jar:?]
	at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:64) ~[ProtocolSupport.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: java.lang.UnsupportedOperationException: Failed to init spigot platform
		at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:26) ~[ProtocolSupport.jar:?]
		at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:64) ~[ProtocolSupport.jar:?]
		at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.19.jar:git-Paper-81]
		at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.jar:git-Paper-81]
		at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-81]
		at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/inventory/CraftItemStack
		at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:23) ~[ProtocolSupport.jar:?]
		... 6 more
	Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.inventory.CraftItemStack
		at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
		at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
		at protocolsupport.zplatform.ServerPlatform.detect(ServerPlatform.java:23) ~[ProtocolSupport.jar:?]
		... 6 more
[14:48:21] [Server thread/INFO]: [DriveBackupV2] Loading DriveBackupV2 v1.6.0
[14:48:21] [Server thread/INFO]: [GriefPrevention] Loading GriefPrevention v16.18
[14:48:21] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.2
[14:48:21] [Server thread/INFO]: [PlayerKits] Loading PlayerKits v2.24.3
[14:48:21] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.0.5-SNAPSHOT
[14:48:21] [Server thread/INFO]: [FastLogin] Loading FastLogin v1.12-SNAPSHOT-ed45fad
[14:48:21] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:48:21] [Server thread/INFO]: [ProtocolSupport] Enabling ProtocolSupport v1.18.1-1
[14:48:21] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[14:48:21] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[14:48:21] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[14:48:21] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[14:48:21] [Server thread/INFO]: Preparing level "Adhisiya"
[14:49:04] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:49:10] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:10] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:10] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:10] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:11] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:12] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:12] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:13] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:14] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:14] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:14] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:15] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:15] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:16] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:16] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:17] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:18] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:18] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:18] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:19] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:19] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:20] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:20] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:21] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:22] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:22] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:22] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:23] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:23] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:24] [Server thread/INFO]: Time elapsed: 19189 ms
[14:49:24] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[14:49:26] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:27] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:27] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:27] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:27] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:27] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:27] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:27] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:28] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:28] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:29] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:29] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:30] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:30] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:31] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:31] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:32] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:32] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:33] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:33] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:34] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:35] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:35] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:35] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:36] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:36] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:37] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:37] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:38] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:38] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:38] [Server thread/INFO]: Time elapsed: 14643 ms
[14:49:38] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[14:49:40] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:40] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:40] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:41] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:41] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:41] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:41] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:42] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:42] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:43] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:43] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:44] [Server thread/INFO]: Preparing spawn area: 0%
[14:49:44] [Server thread/INFO]: Time elapsed: 5847 ms
[14:49:44] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v21.2
[14:49:46] [Server thread/INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
[14:49:46] [Server thread/INFO]: [CoreProtect] Using SQLite for data storage.
[14:49:46] [Server thread/INFO]: --------------------
[14:49:46] [Server thread/INFO]: [CoreProtect] Enjoy CoreProtect? Join our Discord!
[14:49:46] [Server thread/INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[14:49:46] [Server thread/INFO]: --------------------
[14:49:46] [Server thread/INFO]: [SimpleTpa] Enabling SimpleTpa v6.1*
[14:49:46] [Server thread/INFO]: [SimpleTpa] If you need support contact me at https://discord.gg/SZUkza9
[14:49:46] [Server thread/INFO]: [SimpleTpa] Simple Tpa has been enabled on version 6.1
[14:49:46] [Server thread/INFO]: Enabled metrics. You may opt-out by changing plugins/bStats/config.yml
[14:49:46] [Server thread/INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta2-b2453
[14:49:47] [Server thread/INFO]: [AuthMe] SQLite Setup finished
[14:49:48] [Server thread/INFO]: [AuthMe] No supported permissions system found! Permissions are disabled!
[14:49:49] [Server thread/WARN]: [AuthMe] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[14:49:49] [Server thread/INFO]: [AuthMe] AuthMe 5.6.0-beta2 build n.2453 successfully enabled!
[14:49:49] [Server thread/INFO]: [floodgate] Enabling floodgate v2.2.0-SNAPSHOT (b70-6e2c19f)
[14:49:52] [Server thread/WARN]: [floodgate] Loaded class protocolsupport.protocol.ConnectionImpl from ProtocolSupport v1.18.1-1 which is not a depend or softdepend of this plugin.
[14:49:52] [Server thread/INFO]: [ProtocolSupport] Login threads keep alive time: 60
[14:49:52] [Server thread/INFO]: [DriveBackupV2] Enabling DriveBackupV2 v1.6.0
[14:49:56] [Server thread/INFO]: [DriveBackupV2] Config loaded!
[14:49:56] [Server thread/INFO]: [DriveBackupV2] Scheduling a backup to run every 60 minutes
[14:49:56] [Server thread/INFO]: [DriveBackupV2] Metrics started
[14:49:56] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.18
[14:49:56] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[14:49:57] [Server thread/INFO]: [GriefPrevention] 0 total claims loaded.
[14:49:59] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[14:49:59] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
[14:50:00] [Server thread/INFO]: [GriefPrevention] Boot finished.
[14:50:00] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.2
[14:50:01] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[14:50:01] [Server thread/INFO]: [PlayerKits] Enabling PlayerKits v2.24.3
[14:50:02] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: playerkits [2.24.3]
[14:50:02] [Server thread/INFO]: [PlayerKits] Has been enabled! Version: 2.24.3
[14:50:02] [Server thread/INFO]: [PlayerKits] Thanks for using my plugin!  ~Ajneb97
[14:50:03] [Server thread/INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.0.5-SNAPSHOT
[14:50:07] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[14:50:07] [Server thread/INFO]: [Geyser-Spigot] 
[14:50:07] [Server thread/INFO]: [Geyser-Spigot] Loading Geyser version 2.0.5-SNAPSHOT (git-master-f4a5ccb)
[14:50:07] [Server thread/INFO]: [Geyser-Spigot] 
[14:50:07] [Server thread/INFO]: [Geyser-Spigot] ******************************************
[14:50:34] [Network Listener - #0/INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:25834
[14:50:35] [Server thread/INFO]: [Geyser-Spigot] Done (27.933s)! Run /geyser help for help!
[14:50:35] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-ed45fad
[14:50:37] [Server thread/WARN]: [FastLogin] Disabling Minecraft proxy configuration. Assuming direct connections from now on.
[14:50:38] [Server thread/INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Starting...
[14:50:38] [Server thread/INFO]: [fastlogin.hikari.HikariDataSource] FastLogin - Start completed.
[14:50:38] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: FastLogin [1.12-SNAPSHOT-ed45fad]
[14:50:39] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[14:50:39] [Server thread/INFO]: Running delayed init tasks
[14:50:39] [Server thread/INFO]: 0 placeholder hook(s) registered!
[14:50:39] [Server thread/INFO]: Done (176.677s)! For help, type "help"
[14:50:39] [Server thread/INFO]: Timings Reset
[14:50:39] [Craft Scheduler Thread - 6 - AuthMe/INFO]: [AuthMe] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[14:50:39] [Craft Scheduler Thread - 6 - AuthMe/WARN]: [AuthMe] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[14:50:39] [Craft Scheduler Thread - 6 - AuthMe/INFO]: [AuthMe] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[14:50:39] [Craft Scheduler Thread - 7 - DriveBackupV2/INFO]: [DriveBackupV2] Checking for updates...
[14:50:39] [Craft Scheduler Thread - 6 - AuthMe/WARN]: [AuthMe] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[14:50:40] [Server thread/INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[14:50:47] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5186ms or 103 ticks behind
[14:50:53] [Server thread/INFO]: Plugins (11): AuthMe, CoreProtect, DriveBackupV2, FastLogin, floodgate, Geyser-Spigot, GriefPrevention, PlaceholderAPI, PlayerKits, ProtocolSupport, SimpleTpa*
[14:51:28] [Network Listener - #0/INFO]: [Geyser-Spigot] /27.61.212.251:62911 tried to connect!
[14:51:28] [Network Listener - #0/INFO]: [Geyser-Spigot] /27.61.212.251:62911 tried to connect!
[14:51:28] [Network Listener - #0/INFO]: [Geyser-Spigot] /27.61.212.251:62911 tried to connect!
[14:51:35] [Network Listener - #2/INFO]: [Geyser-Spigot] Player connected with username PRINCE KUMAR 19
[14:51:35] [defaultEventLoopGroup-5-2/INFO]: [Geyser-Spigot] PRINCE KUMAR 19 (logged in as: PRINCE_KUMAR_19) has connected to the Java server
[14:51:37] [Server thread/INFO]: /27.61.212.251:0 lost connection: Disconnected
[14:51:37] [Geyser Spigot connection thread-4-3/INFO]: [floodgate] Floodgate player logged in as .PRINCE_KUMAR_19 disconnected
[14:51:37] [defaultEventLoopGroup-5-2/INFO]: [Geyser-Spigot] PRINCE KUMAR 19 has disconnected from the Java server because of Internal Exception: java.lang.NullPointerException

### Plugin version

v1.12-SNAPSHOT-ed45fad

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
>java.lang.UnsupportedOperationException: No supported platform detected

FastLogin without any Minecraft proxies requires ProtocolLib or ProtocolSupport. In this case ProtocolSupport failed to initialize.

**Comment by Smart123s** [comment]
You are using 1.18.1 ProtocolSupport on a 1.19 server. And AFIK, there's no 1.19 ProtocolSupport.

> [14:47:42] [Server thread/INFO]: Starting minecraft server version 1.19
> [...]
> [14:48:21] [Server thread/INFO]: [ProtocolSupport] Enabling ProtocolSupport v1.18.1-1
